FROM centos:7

RUN curl https://copr.fedorainfracloud.org/coprs/g/ansible-service-broker/ansible-service-broker-nightly/repo/epel-7/group_ansible-service-broker-ansible-service-broker-nightly-epel-7.repo -o /etc/yum.repos.d/asb.repo
RUN yum -y install epel-release && yum -y install apb && yum clean all

WORKDIR /mnt

ENTRYPOINT ["apb"]
CMD ["-h"]

LABEL RUN docker run --rm -v \${PWD}:/mnt:z -u \${SUDO_UID} \${IMAGE}
