FROM centos:7

RUN yum -y install python-virtualenv git && yum clean all
RUN virtualenv /opt/apb
RUN git clone https://github.com/fusor/ansible-playbook-bundle
RUN source /opt/apb/bin/activate \
 && pip install -U pip setuptools
RUN source /opt/apb/bin/activate \
 && cd ansible-playbook-bundle \
 && pip install -r src/requirements.txt \
 && python setup.py install
RUN echo -ne "#!/bin/bash\nsource /opt/apb/bin/activate\napb \$@" > /usr/local/bin/apb-wrapper
RUN chmod +x /usr/local/bin/apb-wrapper

WORKDIR /mnt

ENTRYPOINT ["apb-wrapper"]
CMD ["-h"]

LABEL RUN docker run --rm -v \${PWD}:/mnt:z -u \${SUDO_UID} \${IMAGE}
